version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules/alert-rules.yml:/etc/prometheus/rules/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle' 
  
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100
  
  alert-manager:
    container_name: alert-manager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alerts/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox_exporter
    ports:
      - "9115:9115"

volumes:
  grafana-storage:
