global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alert-manager:9093']  # fixed here too

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # This is fine, Prometheus scrapes itself

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # ✅ Fix here

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://localhost:9115
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # ✅ Fix here
